/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        return "Hello Mqtt!";
    }

    public static void main(String[] args) {
        SubExample.main(args);
    }
}
